### ISSUE TITLE
Helm hook weight is wrong

### ISSUE THREAD

**Issue by jenciso** [mkdev-me/helm-lightning-course#1]
In order to apply the configmap resource first than job, the hook weight value should < 0, e.g. -1

https://github.com/mkdev-me/helm-lightning-course/blob/9ca6ce8c8850fa9aa87d5c0b4bd3f18af5200465/templates/post-upgrade.yaml#L6

**Comment by Fodoj** [comment]
@jenciso you are totally right, good catch! It stills works as-is because even though Job will be created before ConfigMap, when Job's pods are running the ConfigMap will be already in place - and if not, we will just get reconcile pretty fast in any case. But looking at code, it's confusing! I've changed it to "-1".
